language: node_js
node_js:
  - "6"
  - "6.1"
  - "5"

addons:
  code_climate:
    repo_token: c011b67e8a01499f70e4cdf578edd31500358c40e25bfc3555d3b70b45cd032b

before_script:
  - npm install -g codeclimate-test-reporter

after_script:
  - codeclimate-test-reporter < dist/public/coverage/lcov.info
